### ISSUE TITLE
Zoom in feature in graph in parade

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-parade#40]
The zoom-in slider does not work, erroring, when the graph feature of Parade is switched on.

![screen shot 2018-05-16 at 10 53 32](https://user-images.githubusercontent.com/2478303/40110325-9b19a64c-58f7-11e8-8377-ae34f2e97181.png)

In the graphs as shown below, it would be very useful to be able to zoom in, to properly discern the points clustered close to each other.

![screen shot 2018-05-16 at 10 53 37](https://user-images.githubusercontent.com/2478303/40110284-8091282c-58f7-11e8-8583-3db568450f9a.png)

cc @will-moore @jburel @chris-allan

**Comment by pwalczysko** [comment]
http://web-dev-merge.openmicroscopy.org/webclient/?show=image-118479   user-3

**Comment by chris-allan** [comment]
The plot needs a lot of work. I am fundamentally not convinced it is even a good idea to have thumbnails there in the first place.

I would propose that we not tackle small features like this but rather address the component design as a whole at a later date.

**Comment by pwalczysko** [comment]
Understood about not having the thumbs there, instead, simple points or whatever else would be more appropriate.

**Comment by pwalczysko** [comment]
This is actually solved, closing.
