### ISSUE TITLE
Webclient controls while in parade

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-parade#48]
Sorry, I cannot find the original issue here, neither in Open nor in Closed.
So, opening a new issue.

   - have a parade graph on display in central pane
   - go to right-hand pane, click on some control, e.g. addition of Tag (the plus sign)
   - observe that the popup of the Tag window happens under the graph of parade in central pane, and the control inside the Tag window are not possible to click

Note: this happens also if the left-hand pane (LHP)
![screen shot 2018-08-25 at 20 25 52](https://user-images.githubusercontent.com/2478303/44621823-17f80300-a8a5-11e8-9410-96ecc3eafdb5.png)
 tree controls are deployed, such as Rendering settings on Dataset from context menu on LHP

**Comment by will-moore** [comment]
Fixed in https://github.com/ome/omero-parade/pull/74
