### ISSUE TITLE
Bulk annotations on Dataset

### ISSUE THREAD

**Issue by will-moore** [ome/omero-parade#56]
Currently you have to create Bulk Annotations at the Project level, but support of the Dataset was preferred in: https://www.openmicroscopy.org/qa2/qa/feedback/27391/

NB: This is also not supported by the ```metadata``` plugin as noted in the link.

**Comment by sbesson** [comment]
I think https://github.com/ome/omero-metadata/pull/5 and https://github.com/ome/omero-metadata/pull/15 covered a few scenarios where data can be annotated at the Dataset level i.e. with the latest release version of the library, there should be a few ways to annotate a Dataset with a bulk annotation.

**Comment by manics** [comment]
This definitely works with the latest metadata plugin, and https://github.com/ome/scripts/pull/148 adds support for doing it in OMERO.scripts.
